name: GitHub Actions Demo
on: [push]
jobs:
  release-cicd:
    environment: Release Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDk 11
        if: success()
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build and Unit test
        if: success()
        run: mvn clean install

