name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        if: success()
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Configure Git user
        run: |
          git config user.email "phuongnam.nextx@gmail.com"
          git config user.name "NamNextx"
      - name: Publish JAR
        run: mvn release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}